<?php

function skimlinks_page_bottom(array &$page_bottom) {
  $config = \Drupal::config('skimlinks.settings');
  $id = $config->get('account');

  if (!empty($id) && !_skimlinks_is_admin_page()) {
    $page_bottom['skimlinks'] = [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => '',
      '#attributes' => array('src' => "//s.skimresources.com/js/{$id}.skimlinks.js"),
    ];
  }
}

/**
 * Checks for admin pages or node edit pages
 * @return  bool  Returns TRUE for admin pages
 */
function _skimlinks_is_admin_page() {
  // Admin
  $route = \Drupal::routeMatch()->getRouteObject();
  if (\Drupal::service('router.admin_context')->isAdminRoute($route)) {
    return TRUE;
  }

  // Node edit
  $current_path = \Drupal::service('path.current')->getPath();
  if (preg_match('/node\/(\d+)\/edit/', $current_path, $matches)) {
    return TRUE;
  }

  return FALSE;
}